version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
      - VITE_BFF_API_URL=http://localhost:3001
    depends_on:
      - bff

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./bff:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - NODE_ENV=development
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - USER_SERVICE_URL=http://user-service:3002
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - user-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    volumes:
      - ./user-service:/app
      - /app/node_modules
    environment:
      - PORT=3002
      - NODE_ENV=development
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - ALLOWED_ORIGINS=http://localhost:3001,http://localhost:5173

  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    volumes:
      - ./task-service:/app
      - /app/node_modules
    environment:
      - PORT=3003
      - NODE_ENV=development
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - ALLOWED_ORIGINS=http://localhost:3001,http://localhost:5173
      - MONGODB_URI=mongodb://mongodb:27017/tasks
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tasks

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - mongodb

volumes:
  mongodb_data:
